kursach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('navigate.urls')),
    path('navigate/', include('navigate.urls')),
    path('navigate/', include('django.contrib.auth.urls')),
]

navigate/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from datetime import date
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _



# class Role(models.Model):
#     name = models.CharField(max_length=100, verbose_name='Наименование')
#     def __str__(self):
#         return self.name

    # class Meta:
    #     verbose_name = "Роль"
    #     verbose_name_plural = "Роли"

class CustomUser(AbstractUser):

    ROLE_CHOICES = [
        ('Клиент', 'Клиент'),
        ('Сотрудник', 'Сотрудник'),
        ('Водитель', 'Водитель'),
        ('Администратор', 'Администратор'),

    ]
    first_name = models.CharField(max_length=50, verbose_name='Имя', null=True)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', null=True)
    patronymic = models.CharField(max_length=50, verbose_name='Отчество', null=True)
    phone_number = models.CharField(max_length=11, verbose_name='Номер телефона', null=True)
    passport = models.CharField(max_length=10, verbose_name='Серия номер паспорта', unique=True, null=True)
    date_of_birth = models.DateField(verbose_name='Дата рождения', null=True)
    role = models.CharField(max_length=200,
                              choices=ROLE_CHOICES,
                              default='Клиент',
                              verbose_name='Роль')
    def __str__(self):
        if(self.role == 'Клиент'):
            return "ФИО: " + str(self.last_name) + " " + self.first_name + " " +  self.patronymic + " " + " Паспорт: " + str(self.passport)
        else:
            return "Логин:  " + self.username + " Роль: " + str(self.role)
    class Meta:
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def save(self, *args, **kwargs):

        if self.role is None and not self.is_superuser:
            self.role = "Клиент"
        elif self.is_superuser:
            self.role = "Администратор"
        super().save(*args, **kwargs)

    def clean(self):

        if self.date_of_birth:
            today = date.today()
            age = today.year - self.date_of_birth.year - (
                    (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

            if age < 14:
                raise ValidationError({
                    'date_of_birth': _('Пользователь должен быть старше 14 лет.')
                })
        if not self.phone_number.isdigit() or len(self.phone_number) != 11:
            raise ValidationError({
                'phone_number': _('Номер телефона должен содержать 11 цифр.')
            })
        if not self.passport.isdigit() or len(self.passport) != 10:
            raise ValidationError({
                'passport': _('Паспорт должен содержать 10 цифр.')
            })

class CargoCategory(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    coefficient = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Коэфициент перевозки')
    comments = models.CharField(max_length=500, verbose_name='Комментарии', null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({self.comments})  коэфициент:{self.coefficient}"

    class Meta:
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

class Warehouse(models.Model):
    region = models.CharField(max_length=200, verbose_name='Регион')
    city = models.CharField(max_length=200, verbose_name='Город')
    street = models.CharField(max_length=200, verbose_name='Улица')
    home = models.CharField(max_length=200, verbose_name='Дом')
    corpus = models.CharField(max_length=200, verbose_name='Корпус', null=True, blank=True)
    def __str__(self):
        if(str(self.corpus) == "None"):
            return str(self.region) + ", г." + str(self.city) + ", ул." + str(self.street) + ", д." + str(self.home)
        else:
            return str(self.region) + ", г." + str(self.city) + ", ул." + str(self.street) + ", д." + str(self.home) + ", к." + str(self.corpus)

    class Meta:
        verbose_name = "Склад"
        verbose_name_plural = "Склады"

class Car(models.Model):
    STATUS_CHOICES = [
        ('На базе', 'На базе'),
        ('Назначен водитель', 'Назначен водитель'),
        ('Ремонт', 'Ремонт'),
        ('Списана', 'Списана'),

    ]
    vin = models.CharField(max_length=17, verbose_name='VIN', unique=True)
    state_number = models.CharField(max_length=9, verbose_name='Гос.номер')
    stamp = models.CharField(max_length=200, verbose_name='Марка')
    model = models.CharField(max_length=200, verbose_name='Модель')
    status = models.CharField(max_length=200,
                              choices=STATUS_CHOICES,
                              default='На базе',
                              verbose_name='Статус')
    driver_id = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  limit_choices_to={'role': "Водитель"},
                                  on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Водитель')
    def __str__(self):
        return str(self.state_number)

    class Meta:
        verbose_name = "Машину"
        verbose_name_plural = "Машины"

    def clean(self):
        if  len(self.vin) != 17:
            raise ValidationError({
                'vin': _('VIN номер должен содержать 17 символов.')
            })

        if len(self.vin) < 8 :
            raise ValidationError({
                'state_number': _('гос. номер должен состоять из 8 или 9 символдов')
            })

class PointIssue(models.Model):
    region = models.CharField(max_length=200, verbose_name='Регион')
    city = models.CharField(max_length=200, verbose_name='Город')
    street = models.CharField(max_length=200, verbose_name='Улица')
    home = models.CharField(max_length=10, verbose_name='Дом')
    corpus = models.CharField(max_length=10, verbose_name='Корпус', null=True, blank=True)
    warehouse_id = models.ForeignKey('Warehouse', on_delete=models.SET_NULL,null=True, verbose_name='Cклад')

    class Meta:
        verbose_name = "Пункт выдачи"
        verbose_name_plural = "Пункты выдачи"

    def __str__(self):
        if (str(self.corpus) == "None"):
            return str(self.region) + ", г." + str(self.city) + ", ул." + str(self.street) + ", д." + str(self.home)
        else:
            return str(self.region) + ", г." + str(self.city) + ", ул." + str(self.street) + ", д." + str(
                self.home) + ", к." + str(self.corpus)




class Package(models.Model):
    STATUS_CHOICES = [
        ('Принят от клиента', 'Принят от клиента'),
        ('Отправлен на склад', 'Отправлен на склад'),
        ('Отправлен на склад в город назначения', 'Отправлен на склад в город назначения'),
        ('Принят на складе в городе назначения', 'Принят на складе в городе назначения'),
        ('Отправлен в пункт выдачи', 'Отправлен в пункт выдачи'),
        ('Принят в пункте выдачи', 'Принят в пункте выдачи'),
        ('Утерян', 'Утерян'),
        ('Заявка на перевозку', 'Заявка на перевозку'),
        ('Утилизирован', 'Утилизирован'),
        ('Выдан', 'Выдан'),
    ]

    client_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name='Packages_as_client',
        verbose_name='Клиент',
        limit_choices_to={'role': "Клиент"},
        null=True,
    )
    comments = models.CharField(max_length=500, verbose_name='Комментарии', null=True, blank=True)
    sending_address = models.ForeignKey(
        'PointIssue',
        on_delete=models.SET_NULL,
        related_name='Packages_as_sending_address',
        verbose_name='Адрес отправки',
        null=True,
    )
    delivery_address =models.ForeignKey(
        'PointIssue',
        on_delete=models.SET_NULL,
        related_name='Packages_as_delivery_address',null=True,
        verbose_name='Адрес доставки',
    )
    weight = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Вес(кг)')
    date_of_receipt = models.DateField(verbose_name='Дата отправки')
    delivery_date = models.DateField(verbose_name='Дата доставки в пункт выдачи', null=True, blank=True,)
    date_of_issue = models.DateField(verbose_name='Дата выдачи', null=True, blank=True,)
    length = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Длина(м)')
    height = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Высота(м)')
    width = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ширина(м)')
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость доставки')
    cargo_category = models.ForeignKey('CargoCategory', on_delete=models.SET_NULL, null=True,
                                         verbose_name='Категория груза')
    status = models.CharField(max_length=200,
                              choices=STATUS_CHOICES,
                              default='Заявка на перевозку',
                              verbose_name='Статус')
    car_id = models.ForeignKey('Car', on_delete=models.SET_NULL, null=True, blank=True,
                                       verbose_name='Номер Машины')

    class Meta:
        verbose_name = "Посылку"
        verbose_name_plural = "Посылки"


    def clean(self):
        super().clean()

        if self.sending_address == self.delivery_address:
            raise ValidationError(_('Адрес доставки и адрес отправки не может совпадать'))


        if self.date_of_receipt and self.date_of_receipt < date.today():
            raise ValidationError({'date_of_receipt': _('Дата отправки не может быть раньше текущей даты.')})


navigate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Package, PointIssue, CargoCategory
from  django.shortcuts import render
from django.forms.widgets import SelectDateWidget

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'passport', 'date_of_birth',
                  'username')
        widgets = {
            'date_of_birth': forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                                 format='%Y-%m-%d')
        }




class CustomUserChangeForm(UserChangeForm):
    model = CustomUser
    fields = ('first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'passport', 'date_of_birth',
              'username')
    widgets = {
        'date_of_birth': forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                             format='%Y-%m-%d')
    }

class PakagesForm(forms.ModelForm):

    cost = forms.DecimalField(
        label='Стоимость доставки',
        widget = forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = Package
        fields = [ 'sending_address', 'delivery_address', 'weight', 'length', 'height','date_of_receipt',
                  'width', 'comments', 'cargo_category', 'cost', 'status']
        widgets = {
            'date_of_receipt' : forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                                         format='%Y-%m-%d'),
            'comments' : forms.TextInput(attrs={'placeholder': 'Описание посылки'}),
            'status' : forms.TextInput(attrs={'readonly': 'readonly'}),
        }

class PakagesEmployeeForm(forms.ModelForm):
    STATUS_CHOICES = [
        ('Принят от клиента', 'Принят от клиента'),
        ('Отправлен на склад', 'Отправлен на склад'),
        ('Отправлен на склад в город назначения', 'Отправлен на склад в город назначения'),
        ('Принят на складе в городе назначения', 'Принят на складе в городе назначения'),
        ('Отправлен в пункт выдачи', 'Отправлен в пункт выдачи'),
        ('Принят в пункте выдачи', 'Принят в пункте выдачи'),
        ('Утерян', 'Утерян'),
        ('Заявка на перевозку', 'Заявка на перевозку'),
        ('Утилизирован', 'Утилизирован'),
        ('Выдан', 'Выдан'),
    ]
    cost = forms.DecimalField(
        label='Стоимость доставки',
        widget = forms.TextInput(attrs={'readonly': 'readonly'}))
    status = forms.ChoiceField(choices=STATUS_CHOICES,initial="Принят от клиента")
    class Meta:
        model = Package
        fields = ['client_id', 'sending_address', 'delivery_address', 'weight', 'length', 'height', 'date_of_receipt',
                  'width', 'comments', 'cargo_category', 'cost', 'car_id', 'status']
        widgets = {
            'date_of_receipt' : forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                                         format='%Y-%m-%d'),
            'comments' : forms.TextInput(attrs={'placeholder': 'Описание посылки'}),
        }


class PakagesEmployeerForm(forms.ModelForm):

    cost = forms.DecimalField(
        label='Стоимость доставки',
        widget = forms.TextInput(attrs={'readonly': 'readonly'}))
    status = forms.CharField(
        label='Статус',
        widget=forms.TextInput(attrs={'default': 'Принят от клиента'}))
    class Meta:
        model = Package
        fields = [ 'sending_address', 'delivery_address', 'weight', 'length', 'height', 'width', 'date_of_receipt',
                   'comments', 'cargo_category', 'cost', 'status']
        widgets = {
            'date_of_receipt' : forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                                         format='%Y-%m-%d'),
            'comments' : forms.TextInput(attrs={'placeholder': 'Описание посылки'}),

        }



class ChangeUserForm(forms.ModelForm):
    # model = CustomUser
    # fields = ('first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'passport', 'date_of_birth',
    #           'username')
    # date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    #password = forms.CharField(widget=forms.PasswordInput(), required=False)

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'passport', 'date_of_birth',
                   'username')
        widgets = {
            'date_of_birth': forms.DateTimeInput(attrs={'type': 'date', 'required': 'required'},
                                                   format='%Y-%m-%d'),

        }

class PackageEditForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = '__all__'

        widgets = {
            'delivery_date': forms.DateTimeInput(attrs={'type': 'date'},
                                                 format='%Y-%m-%d'),
            'date_of_issue': forms.DateTimeInput(attrs={'type': 'date'},
                                                 format='%Y-%m-%d'),

        }

    def __init__(self, *args, **kwargs):
        super(PackageEditForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name not in ['car_id', 'status', 'delivery_date', 'date_of_issue']:
                field.disabled = True

class PackageFilterForm(forms.Form):
    status_choices = [('', 'Все статусы')] + list(Package.STATUS_CHOICES)
    status = forms.ChoiceField(label='Статус', choices=status_choices, required=False)
    sending_address = forms.ModelChoiceField(label='Адрес отправки', queryset=PointIssue.objects.all(), required=False)
    delivery_address = forms.ModelChoiceField(label='Адрес доставки', queryset=PointIssue.objects.all(), required=False)
    date_of_receipt = forms.DateField(label='Дата отправки', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    delivery_date = forms.DateField(label='Дата Доставки', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    date_of_issue = forms.DateField(label='Дата выдачи', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    cargo_category = forms.ModelChoiceField(label='Категория', queryset=CargoCategory.objects.all(), empty_label='Все категории', required=False)
    client = forms.ModelChoiceField(
        queryset=CustomUser.objects.filter(role='Клиент'),
        required=False,
        empty_label="Все клиенты",
        label = 'Клиент'
    )
    package_id = forms.IntegerField(label='Номер  посылки', required=False)

class DateRangeForm(forms.Form):
    start_date = forms.DateField(label='Начальная дата', widget=SelectDateWidget())
    end_date = forms.DateField(label='Конечная дата', widget=SelectDateWidget())

templates/account.html
{% extends 'base.html' %}
{%load static %}
{% block title %}{{user.username}}{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <h2 style="text-align: center; margin-bottom: 20px;">Личный кабинет</h2>
        <div class="wrapper">
          <div class="wrapper-div">
              <h3>Имя</h3>
              <p>{{user.first_name}}</p>
          </div>
         <div class="wrapper-div">
              <h3>Фамилия</h3>
              <p>{{user.last_name}}</p>
          </div>
          <div class="wrapper-div">
              <h3>Отчетво</h3>
              <p>{{user.patronymic}}</p>
          </div>
            <div class="wrapper-div-line3">
          <div class="wrapper-div">
              <h3>Телефон</h3>
              <p>{{user.phone_number}}</p>
          </div>

            <div class="wrapper-div">
              <h3>Серия номер паспорта</h3>
              <p>{{user.passport}}</p>
            </div>
            <div class="wrapper-div">
              <h3>Дата рождения</h3>
              <p>{{user.date_of_birth}}</p>
            </div>
    </div>
            <div class="wrapper-div-line4">
                <div class="wrapper-div">
                    <h3>Имя пользователя</h3>
                    <p>{{user.username}}</p>
                </div>
                <div class="wrapper-div">
                    <h3>E-mail</h3>
                    <p>{{user.email}}</p>
                </div>
                <div>
                 <a class="chenge-bottom" href="{% url 'password_change' %}">Изменить пароль</a>
                <a class="chenge-bottom" href="{%url 'account_edit'%}" type="submit">Изменить данные</a>
            </div>
            </div>
        </div>
        <div class="command">
            <a class="list-bottom" href="{%url 'mypakeges'%}">Мои посылки</a>
        </div>
  </div>
</main>
{% endblock %}

templates/account_edit.html
{% extends 'base.html' %}
{%load static %}
{% block title %}Изменить данные{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <h2 style="text-align: center; margin-bottom: 20px;">Изменить данные</h2>
        <form action="" method="post" class="form-user-edit">
            {% csrf_token %}
            {{ form.as_p }}
                    <script>
                $(document).ready(function() {
                    $('#id_phone_number').mask('99999999999');
                    $('#id_passport').mask('9999999999');
                });
        </script>

            <input id="user-edit-button" type="submit" value="Изменить" />
        </form>
  </div>
</main>
{% endblock %}

templates/det_package.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container">
        <h1>Детали посылки</h1>
        <dl class="dl-horizontal">
            <dt>Номер посылки:</dt>
            <dd>{{ package.id }}</dd>
            <dt>Клиент:</dt>
            <dd>{{ package.client_id }}</dd>
            <dt>Комментарии:</dt>
            {%if package.comments %}
            <dd>{{ package.comments }}</dd>
            {% else %}
            <dd>-</dd>
            {% endif%}
            <dt>Адрес отправки:</dt>
            <dd>{{ package.sending_address }}</dd>
            <dt>Адрес доставки:</dt>
            <dd>{{ package.delivery_address }}</dd>
            <dt>Вес (кг):</dt>
            <dd>{{ package.weight }}</dd>
            <dt>Дата отправки:</dt>
            <dd>{{ package.date_of_receipt }}</dd>
            <dt>Дата доставки в пункт выдачи:</dt>
            {%if package.delivery_date %}
            <dd>{{ package.delivery_date }}</dd>
            {% else %}
            <dd>-</dd>
            {% endif%}
            <dt>Дата выдачи:</dt>
            {%if package.date_of_issue %}
            <dd>{{ package.date_of_issue }}</dd>
            {% else %}
            <dd>-</dd>
            {% endif%}
            <dt>Длина (м):</dt>
            <dd>{{ package.length }}</dd>
            <dt>Высота (м):</dt>
            <dd>{{ package.height }}</dd>
            <dt>Ширина (м):</dt>
            <dd>{{ package.width }}</dd>
            <dt>Стоимость доставки:</dt>
            <dd>{{ package.cost }}</dd>
            <dt>Категория груза:</dt>
            <dd>{{ package.cargo_category }}</dd>
            <dt>Статус:</dt>
            <dd>{{ package.get_status_display }}</dd>

        </dl>

    </div>
</main>
{% endblock %}

templates/package_create.html

{% extends 'base.html' %}
{%load static %}

{% block content %}
<main>
    <div class="container">


<form class="create-pakeges" method="post">

<!--      <p>-->
<!--    <label for="id_sending_address">Адрес отправки:</label>-->
<!--    <select name="sending_address" required id="id_sending_address">-->
<!--  <option value="" selected>-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->

<!--  <option value="1">Свердловская Область, г.Екатеринбург, ул.Абрикосово, д.543, к.4</option>-->

<!--  <option value="2">Еврейская республика, г.Сочи, ул.Гогема, д.55</option>-->

<!--</select>-->

<!--    <label for="id_delivery_address">Адрес доставки:</label>-->
<!--    <input list="id_delivery_address" placeholder="somebody">-->
<!--    <datalist name="delivery_address"  id="id_delivery_address">-->
<!--    {%for adress in PointIssue %}-->
<!--    <option>{{adress.city}}</option>-->
<!--        {% endfor %}-->
<!--    </datalist>-->
    {% csrf_token %}
    {{ form.as_p }}

    <div class="flex-button">
        <button class="create-button" type="submit" id="calculate">Расчитать стоимость</button>
        <button class="create-button-2" type="submit">Создать</button>
    </div>

</form>

            </div>
</main>

<script>
document.addEventListener('DOMContentLoaded', function(){
document.getElementById("calculate").addEventListener("click", function(e){
    e.preventDefault();
    // Получаем значения веса и ширины
    var weight = parseFloat(document.getElementById("id_weight").value);
    var width = parseFloat(document.getElementById("id_width").value);
    var length = parseFloat(document.getElementById("id_length").value);
    var height = parseFloat(document.getElementById("id_height").value);
    var cargoCategoryId = document.getElementById("id_cargo_category").value;
var cargoCategoryDropdown = document.getElementById("id_cargo_category");

    // Проверяем, являются ли вес и ширина числами
    if (isNaN(weight) || isNaN(width)|| isNaN(length)|| isNaN(height) ||
     weight <= 0 || width <= 0|| length <= 0 || height <= 0) {
      alert("Пожалуйста, введите действительные числовые значения для веса и размера посылки.");
    } else {
      var selectedOption = cargoCategoryDropdown.options[cargoCategoryDropdown.selectedIndex];
        var optionText = selectedOption.text;
        var coefficientIndex = optionText.indexOf("коэфициент:") + 11; // 11 is the length of "коэф:"
        var coefficientString = optionText.substring(coefficientIndex).trim();
        var cargoCoefficient = parseFloat(coefficientString);

        if (isNaN(cargoCoefficient)) {
              alert("Пожалуйста, введите действительные числовые значения для веса и размера посылки.");
            } else {

                  var cost = weight * width * length * height * 250 * cargoCoefficient;
                  document.getElementById("id_cost").value = Math.ceil(cost);
                  }
    }
});
    });
</script>
{% endblock %}

templates/services.html
{% extends 'base.html' %}
{%load static %}
{% block title %}Услуги{% endblock title %}

{% block content %}
<main>
  <div class="container">
      <h2 style="text-align: center; margin-bottom: 20px;">Услуги</h2>
      <img class="loader" src="{% static "image/loader.png" %}" alt="грузчик">
      <div class="serv">
          <h3>Отследить Посылку</h3>
          <div class="serv-1">
            <label>Номер посылки:</label>
              <form  method="get" action="{% url 'services' %}">
                  {% csrf_token %}
                  <div class="serv-1">
            <input placeholder="Введите номер посылки"  class="check" type="text" name="tracking_number">
            <button class="check-bottom" type="submit" name="search_id">Отследить</button>
                  </div>
              </form>
          </div>
          <div class="results">
              {% if package %}
              <h2>Посылка Найдена</h2>
             <div class="finde-pakage">
                 <div class="str-find">
                     <h4>Номер посылки</h4>
                     <p>{{ package.id }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Статус</h4>
                     <p>{{ package.status }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Адрес отправки</h4>
                     <p>{{ package.sending_address }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Адрес доставки</h4>
                     <p>{{ package.delivery_address }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Вес(кг)</h4>
                     <p>{{ package.weight }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Категория</h4>
                     <p>{{ package.cargo_category }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Дата отправкии</h4>
                     <p>{{ package.date_of_receipt }}</p>
                 </div>
                 <div class="str-find">
                     <h4>Дата выдачи</h4>
                     <p>{{ package.date_of_issue }}</p>
                 </div>


             </div>
            {% else %}
                <img class="boxquestion" src="{% static "image/boxquestion.png" %}" alt="кубик">
            {% endif %}</div>

      </div>


<!--<div class="serv">-->
<!--    <h3>Пункты выдачи</h3> -->
<!--    <label for="id_city">Выберите город:</label>-->
<!--    <select id="id_city" name="city">-->
<!--        {% for city_info in cities %}-->
<!--            <option value="{{ city_info.city }}">{{ city_info.city }}</option>-->
<!--        {% endfor %}-->
<!--    </select>-->
<!--    <div id="selected_info">-->
<!--    &lt;!&ndash; The list of delivery points will be displayed here &ndash;&gt;-->
<!--</div>-->
<!--</div>-->
      <div class="serv">
          <h3>Расчитать стоимость и создать заявку на перевозку</h3>
          {% if user.is_authenticated %}
          <p>Если вы отправляете посылку нашей компанией первый раз вам необходимо будет заполнить согласие на обработку
              данных в пункте выдачи или заполнить и принести с собой. Скачать шаблон можно по <a class="forgot-pass" href="#">ссылке </a></p>
          <a class="list-bottom" href="{% url 'createPakages'%}">Расчитать стоимость и создать заявку на перевозку</a>
            {% else %}
          <p id="accsess">Для расчета вам необходимо <a href="{% url 'login' %}" class="login">Войти</a> в аккаут</p>
          {%endif%}
      </div>
  </div>
</main>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function(){
        // Handle city selection change
        $('#id_city').on('change', function(){
            var selectedCity = $(this).val();

            console.log('Selected city:', selectedCity);

            // Make AJAX request to get delivery points
            $.ajax({
                url: '{% url "get_delivery_points" %}',
                data: {'city': selectedCity},
                dataType: 'json',

                success: function(data){
                    console.log('AJAX success:', data);

                    var selectedInfoDiv = $('#selected_info');
                    selectedInfoDiv.empty();

                    var ul = $('<ul>');

                    $.each(data, function(index, point){
                        var liText = point.region + ', г.' + point.city + ', ул.' + point.street + ', д.' + point.home;
                        if (point.corpus) {
                            liText += ', к.' + point.corpus;
                        }

                        var li = $('<li>').text(liText);
                        ul.append(li);
                    });

                    selectedInfoDiv.append(ul);
                },
                error: function(xhr, status, error){
                    console.error('AJAX Error:', status, error);
                }
            });
        });
    });
</script>

{% endblock %}

templates/signup.html

    {% extends 'base.html' %}

    {% block title %}Регистрация{% endblock %}

    {% block content %}
    <main>
    <div class="container">
    <h2 style="text-align: center; margin-bottom: 20px;">Регистрация</h2>
    <form class="form-sign" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <script>
                $(document).ready(function() {
                     $('#id_phone_number').mask('89999999999');
                    $('#id_passport').mask('9999999999');
                    });
        </script>

        <button class="sign-up" type="submit">Зарегистрироваться</button>
    </form>
    </div>
    </main>
    {% endblock content%}